1.Create a NumPy array from the list

[10, 20, 30, 40, 50]


2.Create a NumPy array of numbers from 1 to 20.

3.Find the data type and shape of the array:

arr = np.array([5, 10, 15, 20])


4.Create an array of 10 zeros and another of 10 ones.

5.Create a NumPy array of 5 random integers between 1 and 100.

In [51]:
#1.Create a NumPy array from the list

import numpy as np
array1 = np.arange(10,60,10)
print (array1)


[10 20 30 40 50]


In [52]:
# create a numpy array from 1 to 20.

array2 = np.arange(1,21)
print (array2)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [53]:
# Find the datatype and shape of the array
arr = np.array([5,10,15,20])

# print(arr.shape)
print(np.shape(arr))

print(type(arr))


(4,)
<class 'numpy.ndarray'>


In [54]:
# create an array of zeros and ones of size 10
array1= np.zeros(10)
print(array1)
array2= np.ones(10)
print(array2)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [55]:
# create an array of 5 random integers between 1 and 100

array2= np.random.randint(1,100,5)
array2



array([ 9, 42, 58, 23,  3])

1.arr = np.array([5, 10, 15, 20, 25, 30])

1.1 Extract the first 3 elements

1.2Extract the last 2 elements

1.3Extract only even numbers

2.Create a 3×3 matrix containing numbers from 1 to 9.

3.From the matrix in Question 2:

3.1Extract the second row

3.2Extract the first column

3.3Extract the center element

4.Reshape a 1D array of size 12 into:

a 3×4 matrix

a 2×6 matrix

In [56]:
# 1.arr = np.array([5, 10, 15, 20, 25, 30])

# 1.1 Extract the first 3 elements

# 1.2Extract the last 2 elements

# 1.3Extract only even numbers

arr = np.array([5, 10, 15, 20, 25, 30])

print(arr[:3])

print(arr[3:])

print(arr[arr % 2 == 0])


[ 5 10 15]
[20 25 30]
[10 20 30]


In [57]:
# 2.Create a 3×3 matrix containing numbers from 1 to 9.
arraya= np.random.randint(1,9,(3,3))
print(arraya)

[[2 8 2]
 [5 4 6]
 [4 1 5]]


In [58]:
# 3.From the matrix in Question 2:

# 3.1Extract the second row

# 3.2Extract the first column

# 3.3Extract the center element

print(arraya[1,:])
print()
print(arraya[:,0])
print()
print(arraya[:,1])

[5 4 6]

[2 5 4]

[8 4 1]


In [59]:
# 4.Reshape a 1D array of size 12 into:

# a 3×4 matrix

# a 2×6 matrix

rarray = np.arange(12)
print(rarray)
print()
print(np.shape(rarray))
print()
rearray = rarray.reshape(3,4)
print(rearray)
print()
resarray = rarray.reshape(2,6)
print(resarray)

[ 0  1  2  3  4  5  6  7  8  9 10 11]

(12,)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


1Given:
a = np.array([2, 4, 6])
b = np.array([1, 3, 5])

a.Add, subtract, multiply, and divide the arrays
b.Find a²

2.Find the sum, mean, min, max, and standard deviation of:

arr = np.array([10, 20, 30, 40, 50])

3.Find the row-wise sum and column-wise sum of:

arr = np.array([[1, 2, 3],
                [4, 5, 6]])

In [ ]:
# 1Given:
# a = np.array([2, 4, 6])
# b = np.array([1, 3, 5])

# a.Add, subtract, multiply, and divide the arrays
# b.Find a²

a = np.array([2, 4, 6])
b = np.array([1, 3, 5])

print("Adding the arrays:", a + b)
print("Subtracting the arrays:", a - b)
print("Multiplying the arrays:", a * b)
print("Dividing the arrays:", a / b)
print("Squaring array a:", a**2)

Adding the arrays: [ 3  7 11]
Subtracting the arrays: [1 1 1]
Multiplying the arrays: [ 2 12 30]
Dividing the arrays: [2.         1.33333333 1.2       ]
[ 4 16 36]


In [ ]:
# 2.Find the sum, mean, min, max, and standard deviation of:

# arr = np.array([10, 20, 30, 40, 50])


arr = np.array([10, 20, 30, 40, 50])

print("Sum:", arr.sum())
print("Mean:", arr.mean())
print("Min:", arr.min())
print("Max:", arr.max())
print("Standard Deviation:", arr.std())

Sum: 150
Mean: 30.0
Min: 10
Max: 50
Standard Deviation: 14.142135623730951


In [ ]:
# 3.Find the row-wise sum and column-wise sum of:

# arr = np.array([[1, 2, 3],
#                 [4, 5, 6]])

arr = np.array([[1, 2, 3],
                [4, 5, 6]])

print("sum according to column",np.sum(arr,axis=0))
print("sum according to row",np.sum(arr,axis=1))

sum according to column [5 7 9]
sum according to row [ 6 15]


1.From the array:
arr = np.array([12, 7, 9, 15, 20, 3])

a.Select values greater than 10
b.Replace values less than 10 with 0

2.Given:

scores = np.array([45, 67, 89, 34, 76, 90])


a.Find students who passed (≥ 50)

b.Count how many students failed

In [ ]:
# 1.From the array:
# arr = np.array([12, 7, 9, 15, 20, 3])

# a.Select values greater than 10
# b.Replace values less than 10 with 0


arr = np.array([12, 7, 9, 15, 20, 3])

print("Values greater than 10:",arr[arr>10])
print()
arr[arr<10] = 0
print("replacing value with 0 which is less than 10",arr)
    

[12 15 20]
[12  0  0 15 20  0]


In [ ]:
# 2.Given:

# scores = np.array([45, 67, 89, 34, 76, 90])


# a.Find students who passed (≥ 50)

# b.Count how many students failed

scores = np.array([45, 67, 89, 34, 76, 90])

print("Student who have passed :",scores[scores >= 50])

print("Number of students who failed:", np.count_nonzero(scores <= 50))

Student who have passed : [67 89 76 90]
Number of students who failed: 2


1.Sort the following array:

arr = np.array([30, 10, 40, 20, 50])

2.Find unique values and their counts from:

arr = np.array([1, 2, 2, 3, 3, 3, 4])

In [ ]:
# 1.Sort the following array:
# arr = np.array([30, 10, 40, 20, 50])

arr = np.array([30, 10, 40, 20, 50])
print("shorting the array:",np.sort(arr))


shorting the array: [10 20 30 40 50]
[10 20 30 40 50]


In [ ]:
# Find unique values and their counts from:
# arr = np.array([1, 2, 2, 3, 3, 3, 4])

arr = np.array([1, 2, 2, 3, 3, 3, 4])
unique = np.unique(arr)
print("Unique elements in the array:", unique)

print("Number of unique elements:", np.count_nonzero(unique))

Unique elements in the array: [1 2 3 4]
Number of unique elements: 4


1.Sales Analysis
sales = np.array([1000, 1200, 900, 1500, 1800, 1100])

a.Find total sales
b.Find average sales
c.Find the highest and lowest sales

2.2D Sales Data
sales = np.array([[200, 300, 250],
                  [400, 500, 450],
                  [600, 700, 650]])

a.Find total sales per day
b.Find total sales per product
c.Find the overall total sales

3.Replace all values below the average with the average value in the array:
arr = np.array([10, 20, 30, 40, 50])

In [ ]:
# 1.Sales Analysis
# sales = np.array([1000, 1200, 900, 1500, 1800, 1100])

# a.Find total sales
# b.Find average sales
# c.Find the highest and lowest sales
sales = np.array([1000, 1200, 900, 1500, 1800, 1100])

print("Total sales:", np.sum(sales))
print("Average sales:", np.mean(sales))
print("Lowest sales:", np.min(sales))
print("Highest sales:", np.max(sales))

Total sales: 7500
Average sales: 1250.0
Lowest sales: 900
Highest sales: 1800


In [ ]:
# 2.2D Sales Data
# sales = np.array([[200, 300, 250],
#                   [400, 500, 450],
#                   [600, 700, 650]])

# a.Find total sales per day
# b.Find total sales per product
# c.Find the overall total sales


sales = np.array([[200, 300, 250],
                  [400, 500, 450],
                  [600, 700, 650]])

day_sales=np.sum(sales, axis=1)
print("Total sales for each day:",day_sales)
product_sales = np.sum(sales, axis=0)
print("Total sales for each product:",product_sales)

print("Total sales for all products:",np.sum(sales))



Total sales for each day: [ 750 1350 1950]
Total sales for each product: [1200 1500 1350]
Total sales for all products: 4050


In [ ]:
# 3.Replace all values below the average with the average value in the array:
# arr = np.array([10, 20, 30, 40, 50])


arr = np.array([10, 20, 30, 40, 50])
avg=np.mean(arr)
arr[arr<avg] = avg
print(arr)



[30 30 30 40 50]


1.Create an array of even numbers from 2 to 100
2.Reverse the array

In [124]:

# 1.Create an array of even numbers from 2 to 100
array= np.array([])
for i in range(2,102):
    if i % 2 ==0:
        array= np.append(array,i)
print("Array from 1 to 100 contains only even numbers:",array)
print()

# 2.Reverse the array
reverse = array[::-1]
print("Reverse the array:",reverse)

# print(np.flip(array))

Array from 1 to 100 contains only even numbers: [  2.   4.   6.   8.  10.  12.  14.  16.  18.  20.  22.  24.  26.  28.
  30.  32.  34.  36.  38.  40.  42.  44.  46.  48.  50.  52.  54.  56.
  58.  60.  62.  64.  66.  68.  70.  72.  74.  76.  78.  80.  82.  84.
  86.  88.  90.  92.  94.  96.  98. 100.]

Reverse the array: [100.  98.  96.  94.  92.  90.  88.  86.  84.  82.  80.  78.  76.  74.
  72.  70.  68.  66.  64.  62.  60.  58.  56.  54.  52.  50.  48.  46.
  44.  42.  40.  38.  36.  34.  32.  30.  28.  26.  24.  22.  20.  18.
  16.  14.  12.  10.   8.   6.   4.   2.]
