In [2]:
import numpy as np

In [ ]:
# adding two arrays

array1=np.array([10,20,30,40,50,60,70,80,90,100])
array2 = np.arange(10)
print (array1 + array2)


[ 10  21  32  43  54  65  76  87  98 109]


In [7]:
# check which elements are greater than or equal to 40,
# return boolean array

array3 = array1>= 40
print (array3)

# print the elements
print (array1[array3])

[False False False  True  True  True  True  True  True  True]
[ 40  50  60  70  80  90 100]


In [10]:
array1=np.array([1,2,3,4,5])
# print all the sum of elements
print(array1.sum())
print(np.sum(array1))
# print the minimum value
print(array1.min())
print(np.min(array1))
# print the max value
print(array1.max())
print(np.max(array1))

# get the cube of the elements 
print(np.power(array1,3))
print(array1**3)


15
15
1
1
5
5
[  1   8  27  64 125]
[  1   8  27  64 125]


In [ ]:
a1=np.array([1,2,3])
a2=np.array([4,5,6])
print(np.concatenate([a1,a2]))
a3=np.array([21,22])
print(np.concatenate([a1,a2,a3]))
print(np.concatenate([a1,a3]))

[1 2 3 4 5 6]
[ 1  2  3  4  5  6 21 22]
[ 1  2  3 21 22]
(2,)


In [18]:
a1= np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
a2= np.array([[10,11,12],
              [13,14,15],
              [16,17,18]])
print(np.concatenate([a1,a2])) 
print()
print(np.concatenate([a1,a2], axis=1))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]

[[ 1  2  3 10 11 12]
 [ 4  5  6 13 14 15]
 [ 7  8  9 16 17 18]]
