In [56]:
import numpy as np

In [57]:
# adding two arrays

array1=np.array([10,20,30,40,50,60,70,80,90,100])
array2 = np.arange(10)
print (array1 + array2)


[ 10  21  32  43  54  65  76  87  98 109]


In [58]:
# check which elements are greater than or equal to 40,
# return boolean array

array3 = array1>= 40
print (array3)

# print the elements
print (array1[array3])

[False False False  True  True  True  True  True  True  True]
[ 40  50  60  70  80  90 100]


In [59]:
array1=np.array([1,2,3,4,5])
# print all the sum of elements
print(array1.sum())
print(np.sum(array1))
# print the minimum value
print(array1.min())
print(np.min(array1))
# print the max value
print(array1.max())
print(np.max(array1))

# get the cube of the elements 
print(np.power(array1,3))
print(array1**3)


15
15
1
1
5
5
[  1   8  27  64 125]
[  1   8  27  64 125]


In [60]:
a1=np.array([1,2,3])
a2=np.array([4,5,6])
print(np.concatenate([a1,a2]))
a3=np.array([21,22])
print(np.concatenate([a1,a2,a3]))
print(np.concatenate([a1,a3]))

[1 2 3 4 5 6]
[ 1  2  3  4  5  6 21 22]
[ 1  2  3 21 22]


In [61]:
a1= np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
a2= np.array([[10,11,12],
              [13,14,15],
              [16,17,18]])
print(np.concatenate([a1,a2])) 
print()
print(np.concatenate([a1,a2], axis=1))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]

[[ 1  2  3 10 11 12]
 [ 4  5  6 13 14 15]
 [ 7  8  9 16 17 18]]


1D array split

In [62]:
# split array into 2 parts

spl= np.arange(10)
print(spl)
print(np.split(spl,2))
print(np.split(spl,5))
print(np.split(spl,[6,7]))  # split at index 6 and 7



[0 1 2 3 4 5 6 7 8 9]
[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]
[array([0, 1]), array([2, 3]), array([4, 5]), array([6, 7]), array([8, 9])]
[array([0, 1, 2, 3, 4, 5]), array([6]), array([7, 8, 9])]


In [63]:

a2= np.arange(10)
print(np.array_split(a2,3))

[array([0, 1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]


2D array split


In [64]:
a1= np.arange(80).reshape(4,20)
print(a1)
print()
np.vsplit(a1,2)



[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79]]



[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
         16, 17, 18, 19],
        [20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
         36, 37, 38, 39]]),
 array([[40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55,
         56, 57, 58, 59],
        [60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75,
         76, 77, 78, 79]])]

In [65]:
a1= np.arange(80).reshape(10,8)
print(np.shape(a1))
print()
print(a1)
print()
np.hsplit(a1,4)


(10, 8)

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31]
 [32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47]
 [48 49 50 51 52 53 54 55]
 [56 57 58 59 60 61 62 63]
 [64 65 66 67 68 69 70 71]
 [72 73 74 75 76 77 78 79]]



[array([[ 0,  1],
        [ 8,  9],
        [16, 17],
        [24, 25],
        [32, 33],
        [40, 41],
        [48, 49],
        [56, 57],
        [64, 65],
        [72, 73]]),
 array([[ 2,  3],
        [10, 11],
        [18, 19],
        [26, 27],
        [34, 35],
        [42, 43],
        [50, 51],
        [58, 59],
        [66, 67],
        [74, 75]]),
 array([[ 4,  5],
        [12, 13],
        [20, 21],
        [28, 29],
        [36, 37],
        [44, 45],
        [52, 53],
        [60, 61],
        [68, 69],
        [76, 77]]),
 array([[ 6,  7],
        [14, 15],
        [22, 23],
        [30, 31],
        [38, 39],
        [46, 47],
        [54, 55],
        [62, 63],
        [70, 71],
        [78, 79]])]