numpy array operations


In [1]:
import numpy as np

slicing

In [ ]:
array = np.array([1,2,3,4,5,6,7,8,9])
slicing = array[2:7]
print(slicing)


[3 4 5 6 7]


In [12]:
array_2d =np.array([[1,2,3,4,5,6,7],
                    [11,22,33,44,55,66,77],
                    [111,222,333,444,555,666,777]])
print(array_2d[1,5])
print("select complete row",array_2d[1])
print("select complete column",array_2d[:,3])



66
select complete row [11 22 33 44 55 66 77]
select complete column [  4  44 444]


In [16]:
random =np.random.rand(4,4)
print(random)
print(random[1,2])
print(random[2])
print(random[:,2])

[[0.58728095 0.14927183 0.35543682 0.16567006]
 [0.62048403 0.0298238  0.97141891 0.74517902]
 [0.88235761 0.0663866  0.72220038 0.57773642]
 [0.69462914 0.42894032 0.20778258 0.57780887]]
0.9714189130855668
[0.88235761 0.0663866  0.72220038 0.57773642]
[0.35543682 0.97141891 0.72220038 0.20778258]


shorting

In [29]:
shorted = np.array([1,8,3,3,5,6,2,1,4,5])
print (np.sort(shorted))

shorted_2d = np.array([[111,2],[4,3],[5,6],[12,11],[7,8]])
print(np.sort(shorted_2d, axis=0))

[1 1 2 3 3 4 5 5 6 8]
[[  4   2]
 [  5   3]
 [  7   6]
 [ 12   8]
 [111  11]]
