# 

In [11]:
import numpy as np

import matplotlib.pyplot as plt



In [18]:
aray=np.array([[1, 2, 3],
               [4, 5, 6],
               [7, 8, 9]])

print(aray[2:,1:2])


[[8]]


In [13]:

# column supermarket: id, 2021, 2022, 2023, 2024

sales_data = np.array([
    [1, 12000, 13500, 15000, 17000], # kathmandu
    [2,  9000, 11000, 13000, 16000], # butwal
    [3, 15000, 14500, 15500, 18000], # pokhara
    [4,  8000,  9500, 12000, 14000], # biratnagar
    [5, 20000, 22000, 25000, 30000], # palpa
    [6, 17500, 18000, 19000, 21000]  # dharan
])
# print all the sales except ktm, only year 2022 and 2023
print(sales_data[1:,2:4])

print()


print ("--super market sales analysis--")
print (sales_data.shape)

# print first 3 
print (sales_data[0:3])
print()

# remove last column
print (sales_data[:,:4])
print()
#print column for 2023 and 2024
print (sales_data[:,2:4])

[[11000 13000]
 [14500 15500]
 [ 9500 12000]
 [22000 25000]
 [18000 19000]]

--super market sales analysis--
(6, 5)
[[    1 12000 13500 15000 17000]
 [    2  9000 11000 13000 16000]
 [    3 15000 14500 15500 18000]]

[[    1 12000 13500 15000]
 [    2  9000 11000 13000]
 [    3 15000 14500 15500]
 [    4  8000  9500 12000]
 [    5 20000 22000 25000]
 [    6 17500 18000 19000]]

[[13500 15000]
 [11000 13000]
 [14500 15500]
 [ 9500 12000]
 [22000 25000]
 [18000 19000]]


In [14]:
# total sales per year

print (np.sum(sales_data[:,1:5], axis=0))  # column wise sum


#minimum sales in each city in 4 years
print (np.min(sales_data[:,1:5], axis=1))  # row wise min

# maximum sales in each city in 4 years
print (np.max(sales_data[:,1:5], axis=1))  # row wise max

[ 81500  88500  99500 116000]
[12000  9000 14500  8000 20000 17500]
[17000 16000 18000 14000 30000 21000]


In [15]:
# averaage sales in each city in 4 years
print (np.mean(sales_data[:,1:], axis=1))  # row wise mean


[14375. 12250. 15750. 10875. 24250. 18875.]
