numpy array operations


In [1]:
import numpy as np

slicing

In [2]:
array = np.array([1,2,3,4,5,6,7,8,9])
slicing = array[2:7]
print(slicing)


[3 4 5 6 7]


In [3]:
array_2d =np.array([[1,2,3,4,5,6,7],
                    [11,22,33,44,55,66,77],
                    [111,222,333,444,555,666,777]])
print(array_2d[1,5])
print("select complete row",array_2d[1])
print("select complete column",array_2d[:,3])



66
select complete row [11 22 33 44 55 66 77]
select complete column [  4  44 444]


In [4]:
random =np.random.rand(4,4)
print(random)
print(random[1,2])
print(random[2])
print(random[:,2])

[[0.7319833  0.68895843 0.50970503 0.72004859]
 [0.47568366 0.14580455 0.36915924 0.46937519]
 [0.10315767 0.74854174 0.78413433 0.75718472]
 [0.37671527 0.56765374 0.25678023 0.32352867]]
0.36915924423926505
[0.10315767 0.74854174 0.78413433 0.75718472]
[0.50970503 0.36915924 0.78413433 0.25678023]


shorting

In [5]:
shorted = np.array([1,8,3,3,5,6,2,1,4,5])
print (np.sort(shorted))

shorted_2d = np.array([[111,2],[4,3],[5,6],[12,11],[7,8]])
print(np.sort(shorted_2d, axis=0))

[1 1 2 3 3 4 5 5 6 8]
[[  4   2]
 [  5   3]
 [  7   6]
 [ 12   8]
 [111  11]]


Filtering 

In [6]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])


print("printing greater then 5:",arr[arr > 5])
print("printing smaller then 5:",arr[arr < 5])

## we can put expression in the array indexing

print ("Printing the even num:", arr[arr%2==0])
print ("Printing the odd num:", arr[arr%2!=0])


printing greater then 5: [ 6  7  8  9 10]
printing smaller then 5: [1 2 3 4]
Printing the even num: [ 2  4  6  8 10]
Printing the odd num: [1 3 5 7 9]


Filter with mask

In [7]:
num = np.array([1,2,3,4,5,6,7,8,9,10])
mask = num > 5
print("numbers greater than 5 are :", num[mask])

numbers greater than 5 are : [ 6  7  8  9 10]


In [8]:
condition = np.where(num > 5, num*5, num)
print(condition)
condition = np.where(num > 5, True, False)
print(condition)

[ 1  2  3  4  5 30 35 40 45 50]
[False False False False False  True  True  True  True  True]


In [9]:
array1 = np.array([19,29,33,46,52])
array2 = np.array([66,79,88,92,10])

combined = np.concatenate((array1, array2))
combined = np.sort(combined)
print(combined)

[10 19 29 33 46 52 66 79 88 92]


Array compatibilty

In [10]:
a= np.array([1,2,3,4,5])
b= np.array([6,7,8,9,10])
c= np.array([11,12,13,14,15])

print ("shape compability check:", a.shape==b.shape)


shape compability check: True


In [11]:
# vstack adds row at the bottom
orginal = np.array([[1,2,3,4],[5,6,7,8]])

row = np.array([[9,10,11,12]])

with_row = np.vstack((orginal, row))
print(with_row)


# hstack adds column at the right side
column = np.array([[13],[14],[15]])
with_column = np.hstack((with_row, column))
print(with_column)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3  4 13]
 [ 5  6  7  8 14]
 [ 9 10 11 12 15]]


In [12]:
arr1= np.array([1,2,3,4,5])
delet = np.delete(arr1,3)  #deleting element at index 3
print(delet)


[1 2 3 5]


In [13]:
# slicing 

slic = np.array([10,20,30,40,50,60,70,80,90,100])
# print value 40 to 90 step 2
print (slic[3:9:2])

[40 60 80]


In [14]:
print (slic[:3])

print (slic[1:4])

[10 20 30]
[20 30 40]


In [17]:
data=np.array([1,2,3,4,5,6],ndmin=2)
print(data)
data.ndim #checking dimension of array


[[1 2 3 4 5 6]]


2

In [18]:
arr = np.array([10, 15, 20, 25, 30, 35, 40])

print(arr
[1:4:2]
)

[15 25]
