# 

In [2]:
import numpy as np

import matplotlib.pyplot as plt



In [ ]:

# column supermarket: id, 2021, 2022, 2023, 2024

sales_data = np.array([
    [1, 12000, 13500, 15000, 17000], # kathmandu
    [2,  9000, 11000, 13000, 16000], # butwal
    [3, 15000, 14500, 15500, 18000], # pokhara
    [4,  8000,  9500, 12000, 14000], # biratnagar
    [5, 20000, 22000, 25000, 30000], # palpa
    [6, 17500, 18000, 19000, 21000]  # dharan
])

print ("--super market sales analysis--")
print (sales_data.shape)

# print first 3 
print (sales_data[0:3])
print()

# remove last column
print (sales_data[:,:4])
print()
#print column for 2023 and 2024
print (sales_data[:,2:4])

--super market sales analysis--
(6, 5)
[[    1 12000 13500 15000 17000]
 [    2  9000 11000 13000 16000]
 [    3 15000 14500 15500 18000]]

[[    1 12000 13500 15000]
 [    2  9000 11000 13000]
 [    3 15000 14500 15500]
 [    4  8000  9500 12000]
 [    5 20000 22000 25000]
 [    6 17500 18000 19000]]

[[13500 15000]
 [11000 13000]
 [14500 15500]
 [ 9500 12000]
 [22000 25000]
 [18000 19000]]
