numpy array operations


In [1]:
import numpy as np

slicing

In [2]:
array = np.array([1,2,3,4,5,6,7,8,9])
slicing = array[2:7]
print(slicing)


[3 4 5 6 7]


In [3]:
array_2d =np.array([[1,2,3,4,5,6,7],
                    [11,22,33,44,55,66,77],
                    [111,222,333,444,555,666,777]])
print(array_2d[1,5])
print("select complete row",array_2d[1])
print("select complete column",array_2d[:,3])



66
select complete row [11 22 33 44 55 66 77]
select complete column [  4  44 444]


In [4]:
random =np.random.rand(4,4)
print(random)
print(random[1,2])
print(random[2])
print(random[:,2])

[[0.37584762 0.92654538 0.42161406 0.88346472]
 [0.58748874 0.0488628  0.83458275 0.2224903 ]
 [0.53884547 0.89775548 0.03475273 0.54930401]
 [0.97058996 0.13175446 0.43322027 0.25206733]]
0.8345827501029501
[0.53884547 0.89775548 0.03475273 0.54930401]
[0.42161406 0.83458275 0.03475273 0.43322027]


shorting

In [5]:
shorted = np.array([1,8,3,3,5,6,2,1,4,5])
print (np.sort(shorted))

shorted_2d = np.array([[111,2],[4,3],[5,6],[12,11],[7,8]])
print(np.sort(shorted_2d, axis=0))

[1 1 2 3 3 4 5 5 6 8]
[[  4   2]
 [  5   3]
 [  7   6]
 [ 12   8]
 [111  11]]


Filtering 

In [6]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])


print("printing greater then 5:",arr[arr > 5])
print("printing smaller then 5:",arr[arr < 5])

## we can put expression in the array indexing

print ("Printing the even num:", arr[arr%2==0])
print ("Printing the odd num:", arr[arr%2!=0])


printing greater then 5: [ 6  7  8  9 10]
printing smaller then 5: [1 2 3 4]
Printing the even num: [ 2  4  6  8 10]
Printing the odd num: [1 3 5 7 9]


Filter with mask

In [8]:
num = np.array([1,2,3,4,5,6,7,8,9,10])
mask = num > 5
print("numbers greater than 5 are :", num[mask])

numbers greater than 5 are : [ 6  7  8  9 10]


In [13]:
condition = np.where(num > 5, num*5, num)
print(condition)
condition = np.where(num > 5, True, False)
print(condition)

[ 1  2  3  4  5 30 35 40 45 50]
[False False False False False  True  True  True  True  True]
