numpy array operations


In [19]:
import numpy as np

slicing

In [20]:
array = np.array([1,2,3,4,5,6,7,8,9])
slicing = array[2:7]
print(slicing)


[3 4 5 6 7]


In [21]:
array_2d =np.array([[1,2,3,4,5,6,7],
                    [11,22,33,44,55,66,77],
                    [111,222,333,444,555,666,777]])
print(array_2d[1,5])
print("select complete row",array_2d[1])
print("select complete column",array_2d[:,3])



66
select complete row [11 22 33 44 55 66 77]
select complete column [  4  44 444]


In [22]:
random =np.random.rand(4,4)
print(random)
print(random[1,2])
print(random[2])
print(random[:,2])

[[0.45009449 0.59842897 0.43304096 0.54555519]
 [0.83794031 0.65503694 0.91415241 0.32071889]
 [0.51239196 0.02194296 0.79400935 0.37506314]
 [0.11834054 0.84543393 0.29360194 0.95765966]]
0.9141524054605774
[0.51239196 0.02194296 0.79400935 0.37506314]
[0.43304096 0.91415241 0.79400935 0.29360194]


shorting

In [23]:
shorted = np.array([1,8,3,3,5,6,2,1,4,5])
print (np.sort(shorted))

shorted_2d = np.array([[111,2],[4,3],[5,6],[12,11],[7,8]])
print(np.sort(shorted_2d, axis=0))

[1 1 2 3 3 4 5 5 6 8]
[[  4   2]
 [  5   3]
 [  7   6]
 [ 12   8]
 [111  11]]


Filtering 

In [24]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])


print("printing greater then 5:",arr[arr > 5])
print("printing smaller then 5:",arr[arr < 5])

## we can put expression in the array indexing

print ("Printing the even num:", arr[arr%2==0])
print ("Printing the odd num:", arr[arr%2!=0])


printing greater then 5: [ 6  7  8  9 10]
printing smaller then 5: [1 2 3 4]
Printing the even num: [ 2  4  6  8 10]
Printing the odd num: [1 3 5 7 9]


Filter with mask

In [25]:
num = np.array([1,2,3,4,5,6,7,8,9,10])
mask = num > 5
print("numbers greater than 5 are :", num[mask])

numbers greater than 5 are : [ 6  7  8  9 10]


In [26]:
condition = np.where(num > 5, num*5, num)
print(condition)
condition = np.where(num > 5, True, False)
print(condition)

[ 1  2  3  4  5 30 35 40 45 50]
[False False False False False  True  True  True  True  True]


In [27]:
array1 = np.array([19,29,33,46,52])
array2 = np.array([66,79,88,92,10])

combined = np.concatenate((array1, array2))
combined = np.sort(combined)
print(combined)

[10 19 29 33 46 52 66 79 88 92]


Array compatibilty

In [28]:
a= np.array([1,2,3,4,5])
b= np.array([6,7,8,9,10])
c= np.array([11,12,13,14,15])

print ("shape compability check:", a.shape==b.shape)


shape compability check: True


In [31]:
# vstack adds row at the bottom
orginal = np.array([[1,2,3,4],[5,6,7,8]])

row = np.array([[9,10,11,12]])

with_row = np.vstack((orginal, row))
print(with_row)


# hstack adds column at the right side
column = np.array([[13],[14],[15]])
with_column = np.hstack((with_row, column))
print(with_column)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3  4 13]
 [ 5  6  7  8 14]
 [ 9 10 11 12 15]]


In [33]:
arr1= np.array([1,2,3,4,5])
delet = np.delete(arr1,3)  #deleting element at index 3
print(delet)


[1 2 3 5]


In [37]:
# slicing 

slic = np.array([10,20,30,40,50,60,70,80,90,100])
# print value 40 to 90 step 2
print (slic[3:9:2])

[40 60 80]
