In [1]:
import numpy as np


In [3]:

## creating a numpy array

data =np.array([1,2,3,4,5])
print(data)

array2d = np.array([[1,2,3],[4,5,6]])
print(array2d)


[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]


In [ ]:

array1 = np.array((1,2,3,4,5))
array2 = np.array((10,20,30,40,50))

print ("multiplication of two arrays:",array1*array2)


multiplication of two arrays: [ 10  40  90 160 250]


In [ ]:

num = np.arange(0,10)
print(num)

##creating array with one

one = np.ones((4,5))
print(one)

## crating array with random

random = np.random.random((4,5))
print(random)


[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0.51707207 0.09917029 0.11054727 0.88518175 0.76335337]
 [0.1115425  0.67571084 0.0838894  0.76159729 0.01326424]
 [0.09389712 0.02290198 0.212648   0.74016437 0.39284989]
 [0.66741192 0.16449368 0.77442163 0.2560932  0.42275954]]
[0 1 2 3 4 5 6 7 8 9]
