In [1]:
import numpy as np


In [3]:

## creating a numpy array

data =np.array([1,2,3,4,5])
print(data)

array2d = np.array([[1,2,3],[4,5,6]])
print(array2d)


[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]


In [ ]:

array1 = np.array((1,2,3,4,5))
array2 = np.array((10,20,30,40,50))

print ("multiplication of two arrays:",array1*array2)


multiplication of two arrays: [ 10  40  90 160 250]
