In [1]:
import numpy as np


In [3]:

## creating a numpy array

data =np.array([1,2,3,4,5])
print(data)

array2d = np.array([[1,2,3],[4,5,6]])
print(array2d)


[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]


In [ ]:

array1 = np.array((1,2,3,4,5))
array2 = np.array((10,20,30,40,50))

print ("multiplication of two arrays:",array1*array2)


multiplication of two arrays: [ 10  40  90 160 250]


In [35]:

num = np.arange(0,10)
print(num)

##creating array with one

one = np.ones((4,5))
print(one)

## crating array with random

random = np.random.random((4,5))
print(random)


[0 1 2 3 4 5 6 7 8 9]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0.99308377 0.90289219 0.02351909 0.87613093 0.02937197]
 [0.18923997 0.2060091  0.37896825 0.06417119 0.24387327]
 [0.88114154 0.18316156 0.22166178 0.58192322 0.50246966]
 [0.08240533 0.66869619 0.89795211 0.38300691 0.14130481]]


In [11]:
##vector , matrix and tensor

v1 = np.array([101,102,103])
print("vector:",v1)

m1 =np.array([[1,2,3],[11,12,13],[21,22,23]])
print("matrix:",m1)

t1 = np.array([[[1,2,3],[1,2,3]],[[4,5,6],[4,5,6]]])
print("tensor:",t1)
print("shape of tensor:",t1.shape)
print("dimension of tensor:",t1.ndim)

vector: [101 102 103]
matrix: [[ 1  2  3]
 [11 12 13]
 [21 22 23]]
tensor: [[[1 2 3]
  [1 2 3]]

 [[4 5 6]
  [4 5 6]]]
shape of tensor: (2, 2, 3)
dimension of tensor: 3


In [12]:

dta =np.array([[1,2,3],[11,12,13],[21,22,23]])
print("shape:",dta.shape)
print("dimension:",dta.ndim)
print("size",dta.size)
print("data type",dta.dtype)



shape: (3, 3)
dimension: 2
size 9
data type int32


In [34]:
array = np.arange(1,16)
print("\n",array)

reshapearray = array.reshape(3,5)
print("\n",reshapearray)


flattenarray = reshapearray.flatten()
print("\n",flattenarray)

raveled = reshapearray.ravel() ## shows the orginal array instead of copy
print("\n",raveled)

transposearray = reshapearray.T
print("\n",transposearray)


 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]

 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]

 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]

 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]

 [[ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]
 [ 5 10 15]]


In [30]:
a1 = np.array([[1,2,3,4],[5,6,7,8]])

m = a1.mean()
print("mean:",m)

sta = a1.std()
print("standard deviation:",sta)



mean: 4.5
standard deviation: 2.29128784747792
